# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[1.6,)" # Require at least 1.6.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="forgedcarpet"
version="${file.jarVersion}"
displayName="Forged Carpet"
credits=""
authors="Theo Paris"
description='''

'''
[[dependencies.forgedcarpet]]
    modId="forge"
    mandatory=true
    versionRange="[31.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.forgedcarpet]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
